### ISSUE TITLE
Domain validation not working for subdomains

### ISSUE THREAD

**Issue by OrlandoMD** [GlobalCyberAlliance/domain-security-scanner#19]
Hello - the latest DSS exe is working well overall.  Oddly obtaining the following result when running a set of domains with EXE for `ftpc.fpcusa.com`:

```
ftpc.fpcusa.com 0	invalid domain name	 spf: We couldn't detect any active SPF record for your domain. Please visit https://dmarcguide.globalcyberalliance.org to fix this. bimi: We couldn't detect any active BIMI record for your domain. Please visit https://dmarcguide.globalcyberalliance.org to fix this. dkim: We couldn't detect any active DKIM record for your domain. Please visit https://dmarcguide.globalcyberalliance.org to fix this. dmarc: You do not have DMARC setup! domain: Your domain looks good! No further action needed. mx: You do not have any mail servers setup, so you cannot receive email at this domain.
```

Interactively checking with EasyDMARC online at the following link `https://easydmarc.com/tools/domain-scanner?referred_landing=false&domain=ftpc.fpcusa.com` returns results for SPF, DKIM, and DMARC:

![image](https://github.com/GlobalCyberAlliance/domain-security-scanner/assets/18099390/c2034ab5-9c4b-4f39-966e-9f1f22388751)

The Windows CMD line I'm using:

```
dss.exe scan -t120 -n1.1.1.1,8.8.8.8 -a -f csv < domainsin_01.19.2024.csv > results_out_2024.csv
````

**Comment by wolveix** [comment]
Hey @OrlandoMD!

The error to focus on is the following:
```
scanResult:
    domain: ftpc.fpcusa.com
    error: invalid domain name
```

Looks like our basic domain parser that validates domains before running any checks doesn't qualify subdomains correctly. Thanks for the bug report!

**Comment by wolveix** [comment]
@OrlandoMD this should now be fixed :) Please let us know if you continue to experience issues!
