### ISSUE TITLE
Control on SPF Record

### ISSUE THREAD

**Issue by pydubreucq** [GlobalCyberAlliance/domain-security-scanner#20]
Hi,
First, thanks a lot for your project, it's really cool !

I'm testing it and in my test I wanted to know how SPF Records was analyzed.

So I used a test domain and add bad SPF Records.

I would like to inform you of my results.

Here are the recordings tested

v=spf**2** include:spf.mydomain.com -all

Domain Security Scanner told me that I don't have a SPF Record. It's ok :)
Maybe, that it could be better if it said that I have an error in the SPF records. 

The second record is :

v=spf1 inlude:spf.mydomain.com -all

I made a typo by removing the letter c from the word include.

Domain Security Scanner told me that I have a SPF Record. It's not ok :)

I found these libraries in go for checking SPF compliance :

https://github.com/mileusna/spf
https://github.com/qugu2427/gospf

Bye :)

**Comment by wolveix** [comment]
Hey! 

Your first record would've been ignored due to the invalid starter text. 

Yes, we've actually been working on further record validation, and hope to release that functuonality soon. Thanks!
