### ISSUE TITLE
Test Another DKIM Selector

### ISSUE THREAD

**Issue by pydubreucq** [GlobalCyberAlliance/domain-security-scanner#21]
I tried to test `?dkimSelectors=` parameter and it seems that it's not used.

I tried with my domain mindbaz.com et try a bad selector like selector7 but domain security scanner don't give me an error.

I think he should

**Comment by wolveix** [comment]
Hey! That query parameter from the API is indeed used, you're misunderstanding how it works. You can provide a list of selectors using that parameter, and they will be checked **first** for the domains you're scanning. If a DKIM record isn't found from those selectors, the scanner will then attempt our common list instead.
