### ISSUE TITLE
Odd Error With Latest Windows EXE ? - "unable to unmarshal config values error" | CSV Output Option Request

### ISSUE THREAD

**Issue by OrlandoMD** [GlobalCyberAlliance/domain-security-scanner#23]
I downloaded the latest Windows EXE and placed into its own directory.. however, it's generating the following error:

C:\@DMARC\Test>dss-windows-amd64 scan globalcyberalliance.org github.com google.com -f CSV
2024-08-28T14:09:54-04:00 FTL unable to unmarshal config values error="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!str `8.8.8.8` into []string"

Prior DSS EXE downloaded from Jan 2024 is working well wtih the following command to process a file of domains:
  $ **dss.exe scan < domainsin.csv -fCSV -t120 -n1.1.1.1,8.8.8.8 > results.csv**
   
Could you please advise how best use the latest DSS working in a simliar manner?

**Comment by wolveix** [comment]
Hi @OrlandoMD, I'm out of the office this week so am unable to look into this properly, but I believe your issue can be fixed by deleting the following directory on your system (which will wipe your existing config file for DSS):
```
~/.config/domain-security-scanner
```

On Windows, the full path would look like:
```
C:\Users\YourUser\.config\domain-security-scanner
```

**Comment by OrlandoMD** [comment]
Hello - thank you, that cleared up the error message, and is working fine except for -f CSV option.
Could you please further advise on the very handy, prevously available CSV output formatting option ?

**Comment by wolveix** [comment]
@OrlandoMD my apologies for taking so long to get around to this! I was on holiday when you initially opened the issue, and promptly forgot about it. I found the bug preventing `-f csv` from working, and so you should be good to go now.

Please re-open if you continue to experience issues. Thank you!
