### ISSUE TITLE
Wrong SPF and DMARC validation

### ISSUE THREAD

**Issue by maroofi** [GlobalCyberAlliance/domain-security-scanner#24]
Hi,
Hope you are doing well.

Both SPF and DMARC validations are wrong as they are hard-coded with the following prefix in the code:
DefaultDMARCPrefix = "v=DMARC1;"
DefaultSPFPrefix   = "v=spf1 "

The correct version for DMARC (based on ABNF) is:
`dmarc-version   = "v" *WSP "=" *WSP %x44 %x4d %x41 %x52 %x43 %x31`

and the correct form for SPF is (again ABNF):
```
record           = version terms *SP
version          = "v=spf1"

```

This means using hasprefix() function with the hard-coded "DefaultSPFPrefix" is wrong as it can not detect the followings as valid SPF:
v=sPf1
v=SPF1
V=sPf1
v=SPf1
.....

the same applies to DMARC as well!
Thanks,
Sourena

**Comment by wolveix** [comment]
Hi @maroofi, thanks for taking the time to open this issue.

For SPF, according to RFC7208, you're absolutely correct. The version identifier is case insensitive, and the check should be adjusted: https://datatracker.ietf.org/doc/html/rfc7208#section-12

However, for DMARC, according to RFC7489, your provided ABNF pattern **does** seem to enforce case sensitivity: https://datatracker.ietf.org/doc/html/rfc7489#section-6.4

It's admittedly been a while since I've looked at ABNF, so it's possible that I'm misreading the specification. I'd certainly appreciate your feedback!

**Comment by maroofi** [comment]
Hi,
The problem of DMARC in the code is not case sensitivity.  it's the number of "white spaces" you can put both sides of the equal sign. For example, these are all valid DMARCs but your code can not detect them:
```
v =        DMARC1
v = DMARC1
v=                 DMARC1
```
This can be easily fixed using a regular expression like: `"v\s*=\s*DMARC1"`

Thanks,
Sourena

**Comment by wolveix** [comment]
My apologies, I understood the whitespace, but misinterpreted your message to instead refer to the case sensitivity. Many thanks for this! We'll adjust the code to account for this.

**Comment by maroofi** [comment]
Thank you!

**Comment by wolveix** [comment]
Corrected, thanks again! :)

**Comment by maroofi** [comment]
Hi again,
Ok I saw the commits. The new version is wrong again. Here is the commit:

```
DMARCPrefix = regexp.MustCompile(`^\s*v\s*=\s*DMARC1`) // Matches v=DMARC1 with whitespace (RFC7489).
SPFPrefix   = regexp.MustCompile(`^\s*v\s*=\s*(?i)spf1`)
```

Both of them are wrong. For SPF, you can not have white spaces on sides of the equal sign. It's just case insensitive but without whitespace. also you can not have white spaces before 'v'. the TXT must start with 'v'

For DMARC, you can not have white spaces before 'v'. it must start with 'v'.

I don't know go but I guess you should change it to:
Thanks,
Sourena

**Comment by wolveix** [comment]
My apologies, I got my wires crossed while adjusting the variables for the regex matching. I based the regex off of your given expression, which didn't force `v` to be the first character. I added `^` to address this, though clearly mis-pasted the whitespace allowance. Fixed, let me know if you notice any further issues.
